import type { AirchManifest } from "../../schema/manifest.js";
import type { GeneratedFile } from "../types.js";
import {
  normalizeLineEndings,
  renderArchitectureRulesMarkdown,
  renderCommandsMarkdown,
  renderConventionsMarkdown,
} from "../utils.js";

/**
 * AGENTS.md を生成する
 */
export function generateAgentsMd(manifest: AirchManifest): GeneratedFile {
  const sections: string[] = [];

  // 自動生成ヘッダー
  sections.push("<!-- AUTO-GENERATED BY airch (https://github.com/GenbuHase/Airch) -->");
  sections.push("<!-- DO NOT EDIT MANUALLY. Update airch.yaml and run 'airch generate' to sync. -->");
  sections.push("");

  // タイトル & プロジェクト概要
  sections.push(`# AI Agent Guidelines: ${manifest.project.name}`);
  sections.push("");
  sections.push(`> Architecture Style: **${manifest.project.architecture}**`);
  if (manifest.project.description) {
    sections.push(`> Description: ${manifest.project.description}`);
  }
  sections.push("");
  sections.push(
    "You are an expert AI software engineer assisting in the development of this codebase. " +
      "You MUST strictly adhere to the following architectural boundaries and project conventions at all times. " +
      "Any code that violates forbidden imports or naming conventions will be rejected by CI."
  );
  sections.push("");

  // アーキテクチャ境界
  sections.push("## 1. Architectural Boundaries & Module Rules");
  sections.push(renderArchitectureRulesMarkdown(manifest));
  sections.push("");

  // コーディング規約
  const conventionsMd = renderConventionsMarkdown(manifest);
  if (conventionsMd) {
    sections.push("## 2. Coding Conventions & Standards");
    sections.push(conventionsMd);
    sections.push("");
  }

  // コマンド
  const commandsMd = renderCommandsMarkdown(manifest);
  if (commandsMd) {
    sections.push("## 3. Verification & Execution Commands");
    sections.push(commandsMd);
    sections.push("");
  }

  // チェックリスト
  sections.push("## 4. Pre-Completion Self Checklist for AI");
  sections.push("Before presenting your code to the user or finishing a task, verify:");
  sections.push("1. [ ] Have I imported any modules from a `FORBIDDEN` path?");
  sections.push("2. [ ] Do all newly created files follow the designated naming convention?");
  sections.push("3. [ ] Are all required files present in any new module?");
  sections.push("4. [ ] Did I run the verification commands (e.g. `airch check`) to guarantee boundary integrity?");

  const content = normalizeLineEndings(sections.join("\n"));
  return {
    target: "agents",
    relativePath: "AGENTS.md",
    content,
  };
}
