import type { AirchManifest } from "../../schema/manifest.js";
import type { GeneratedFile } from "../types.js";
import {
  normalizeLineEndings,
  renderArchitectureRulesMarkdown,
  renderCommandsMarkdown,
  renderConventionsMarkdown,
} from "../utils.js";

/**
 * CLAUDE.md を生成する
 */
export function generateClaudeMd(manifest: AirchManifest): GeneratedFile {
  const sections: string[] = [];

  sections.push("<!-- AUTO-GENERATED BY airch: DO NOT EDIT DIRECTLY. Sync via 'airch generate'. -->");
  sections.push("");
  sections.push(`# Claude Code Guidelines: ${manifest.project.name}`);
  sections.push("");
  sections.push(`Architecture: **${manifest.project.architecture}**`);
  if (manifest.project.description) {
    sections.push(`Overview: ${manifest.project.description}`);
  }
  sections.push("");

  // コマンド（Claude Code にとってコマンドは最優先）
  const commandsMd = renderCommandsMarkdown(manifest);
  if (commandsMd) {
    sections.push("## Primary Commands");
    sections.push(commandsMd);
    sections.push("");
  }

  // アーキテクチャ境界
  sections.push("## Architectural Constraints");
  sections.push(renderArchitectureRulesMarkdown(manifest));
  sections.push("");

  // コーディング規約
  const conventionsMd = renderConventionsMarkdown(manifest);
  if (conventionsMd) {
    sections.push("## Code Style & Conventions");
    sections.push(conventionsMd);
    sections.push("");
  }

  const content = normalizeLineEndings(sections.join("\n"));
  return {
    target: "claude",
    relativePath: "CLAUDE.md",
    content,
  };
}
