import type { AirchManifest } from "../../schema/manifest.js";
import type { GeneratedFile } from "../types.js";
import {
  normalizeLineEndings,
  renderArchitectureRulesMarkdown,
  renderCommandsMarkdown,
  renderConventionsMarkdown,
} from "../utils.js";

/**
 * .github/copilot-instructions.md を生成する
 */
export function generateCopilotInstructions(manifest: AirchManifest): GeneratedFile {
  const sections: string[] = [];

  sections.push("<!-- AUTO-GENERATED BY airch: DO NOT EDIT DIRECTLY. Sync via 'airch generate'. -->");
  sections.push("");
  sections.push(`# GitHub Copilot Instructions for ${manifest.project.name}`);
  sections.push("");
  sections.push(`This repository follows a strict **${manifest.project.architecture}** architectural pattern.`);
  if (manifest.project.description) {
    sections.push(`- **Description**: ${manifest.project.description}`);
  }
  sections.push("");
  sections.push("When proposing code completions, refactors, or new files, strictly adhere to these boundaries:");
  sections.push("");

  // アーキテクチャ境界
  sections.push("## Module & Dependency Boundaries");
  sections.push(renderArchitectureRulesMarkdown(manifest));
  sections.push("");

  // コーディング規約
  const conventionsMd = renderConventionsMarkdown(manifest);
  if (conventionsMd) {
    sections.push("## Coding & Language Conventions");
    sections.push(conventionsMd);
    sections.push("");
  }

  // 実行コマンド
  const commandsMd = renderCommandsMarkdown(manifest);
  if (commandsMd) {
    sections.push("## Build & Test Commands");
    sections.push(commandsMd);
    sections.push("");
  }

  const content = normalizeLineEndings(sections.join("\n"));
  return {
    target: "copilot",
    relativePath: ".github/copilot-instructions.md",
    content,
  };
}
