import type { AirchManifest } from "../../schema/manifest.js";
import type { GeneratedFile } from "../types.js";
import {
  normalizeLineEndings,
  renderArchitectureRulesMarkdown,
  renderCommandsMarkdown,
  renderConventionsMarkdown,
} from "../utils.js";

/**
 * .cursorrules を生成する
 */
export function generateCursorRules(manifest: AirchManifest): GeneratedFile {
  const sections: string[] = [];

  sections.push("# AUTO-GENERATED BY airch: DO NOT EDIT DIRECTLY. Sync via 'airch generate'.");
  sections.push("");
  sections.push(`You are working on "${manifest.project.name}", which enforces a strict "${manifest.project.architecture}" architecture.`);
  if (manifest.project.description) {
    sections.push(`Project Overview: ${manifest.project.description}`);
  }
  sections.push("");
  sections.push("CRITICAL DIRECTIVE: You must NEVER generate code that violates module boundaries, imports from forbidden paths, or breaches file naming conventions.");
  sections.push("");

  // モジュールルール
  sections.push("## Architectural Boundary Rules");
  sections.push(renderArchitectureRulesMarkdown(manifest));
  sections.push("");

  // 規約
  const conventionsMd = renderConventionsMarkdown(manifest);
  if (conventionsMd) {
    sections.push("## Coding Conventions");
    sections.push(conventionsMd);
    sections.push("");
  }

  // コマンド
  const commandsMd = renderCommandsMarkdown(manifest);
  if (commandsMd) {
    sections.push("## Verification Commands");
    sections.push(commandsMd);
    sections.push("");
  }

  sections.push("Always keep solutions minimal, idiomatic, and compliant with the architectural boundary rules above.");

  const content = normalizeLineEndings(sections.join("\n"));
  return {
    target: "cursor",
    relativePath: ".cursorrules",
    content,
  };
}
